coverage_service: coveralls   # or 'codecov' or 'html'
xcodeproj: CICDDemo.xcodeproj
scheme: CICDDemo
workspace: CICDDemo.xcworkspace # if you use a workspace instead of just project
# build_directory: ./DerivedData/Build/Intermediates.noindex
output_directory: ./slather-report
ignore: # optional list of files/folders to ignore
  - CICDDemoTests/*
  - fastlane/*
