name: iOS Test Email Cache

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
      - '**'

jobs:
  test:
    runs-on: macos-latest
    outputs:
      test_result: ${{ job.status }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cache Ruby gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install Ruby dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install Bundler and Gems
        run: |
          gem install bundler
          bundle config set path 'vendor/bundle'
          bundle install

      - name: Cache CocoaPods pods
        uses: actions/cache@v3
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod install --verbose

      - name: Run tests with Fastlane
        run: bundle exec fastlane ios test

  notify:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Send email notification with test result
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "${{ needs.test.outputs.test_result == 'success' && '✅' || '❌' }} iOS Test Workflow Completed"
          body: |
            ${{ needs.test.outputs.test_result == 'success' && '✅' || '❌' }} iOS Test Workflow Completed

            • **Status:** ${{ needs.test.outputs.test_result }}
            • **Repository:** ${{ github.repository }}
            • **Event:** ${{ github.event_name }}
            • **Branch:** ${{ github.ref }}
            • **Commit SHA:** ${{ github.sha }}
            • **Workflow URL:** https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            -- GitHub Actions
          to: cristi.chertes@yahoo.com
          from: ${{ secrets.GMAIL_USERNAME }}
          secure: true
