name: Self-hosted Runner Test

on:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: self-hosted
    steps:
      - name: Echo Hello
        run: echo "✅ Runner is working!"

      - name: Print working directory
        run: pwd

      - name: List files
        run: ls -la

      - name: Print GitHub context
        run: echo "${{ toJson(github) }}"
