name: Self-hosted Runner Test

on:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: self-hosted
    steps:
      - name: Debug environment
        run: |
          echo "Shell: $SHELL"
          echo "User: $(whoami)"
          echo "Home: $HOME"
          
      - name: Echo Hello
        run: echo "✅ Runner is working!"

      - name: Print working directory
        run: pwd

      - name: List files
        run: ls -la

      - name: Print GitHub context
        run: echo "${{ toJson(github) }}"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Bundler dependencies (if using Gemfile)
        run: |
          if [ -f Gemfile ]; then
            bundle install
          fi

      - name: Run Fastlane test lane
        run: |
          if [ -f Gemfile ]; then
            bundle exec fastlane test
          else
            fastlane test
          fi
