name: iOS Test

on:
  workflow_dispatch:
    
  push:
    branches:
      - main
      - master
      - '**'   # or any branches you want to run tests on

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Ruby dependencies
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2

    - name: Install Bundler and Gems
      run: |
        gem install bundler
        bundle install || true  # if you use Bundler, else skip

    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        pod repo update
        pod install --verbose

    - name: Run tests with Fastlane
      run: bundle exec fastlane ios test

